# Generated by Django 3.1.2 on 2020-11-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20201102_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
